### ISSUE TITLE
ToDo's:

### ISSUE THREAD

**Issue by DolapoTheCoder** [DolapoTheCoder/blobservice#1]
- [ ] Add Ci/Cd pipeline
- [ ] Make it database agnostic
- [ ] Add thorough testing
- [ ] Add UI to upload database so Product people can use
- [ ] Add environments so testing thoroughly with real data
